services:
  auth:
    build:
      context: services/auth
      dockerfile: Dockerfile
    volumes:
      - ./services/auth/:/app
    env_file:
      - services/auth/env/db.env
    command: fastapi dev auth/main.py --host 0.0.0.0 --port 8081
    ports:
      - "8081:8081"
    networks:
      - app-network
    depends_on:
      auth-db:
        condition: service_started
        restart: true
        required: true
  auth-db:
    image: postgres:17-alpine
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    env_file:
      - docker/auth.db.env
    ports:
      - "5433:5433"
    networks:
      - app-network
volumes:
  auth-db-data:
networks:
  app-network:
    driver: bridge
