services:
  auth:
    build:
      context: auth
      dockerfile: Dockerfile
    command: uvicorn src.main:app --host 0.0.0.0  --port 8080
    ports:
      - "8081:8080"
    networks:
      - app-network
    depends_on:
      auth-db:
        condition: service_started
        restart: true
        required: true
  auth-db:
    image: postgres:17-alpine
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    expose:
      - 5433
    env_file:
      - auth/env/db.env
volumes:
  auth-db-data:
networks:
  app-network:
    driver: bridge
