# Specifies the path where the env file that a service will use will be
# generated to.
target_path = "services/auth/env/auth.env"

# Specifies the path where the env file that will be used by Docker will be
# generated to.
target_path_docker = "docker/auth.env"

# Each TOML table represents an environment variable. The table name
# will be converted into uppercase in the final env file.
# DATABASE_SCHEME=postgresql
# DATABASE_HOST=localhost
# DATABASE_PORT=5433
# DATABASE_NAME=auth_db
# DATABASE_USER=auth_user
# DATABASE_PASSWORD=auth_user_12345
[database_scheme]
value = "postgresql" # The value of the environment variable.

[database_host]
value = "auth-db"

[database_port]
value = 5432
docker_var_name = "pgport"

[database_name]
value = "auth_db"

# The variable name that will be used for this environment variable in the
# env file that will be used by Docker. We may write it here in any case, as
# the environment file will always have the name in uppercase.
docker_var_name = "postgres_db"

[database_user]
value = "auth_user"
docker_var_name = "postgres_user"

[database_password]
value = "auth_user_12345"
docker_var_name = "postgres_password"

[jwt_token_secret]
# Generated with `openssl rand -hex 32`.
value = "892748d74a477dd1323853564b71e361789ada19b9506745af5f701536640b3f"

[access_token_minutes_ttl]
value = 1

[refresh_token_minutes_ttl]
value = 60
